### PR TITLE
sim.py interface now in line with rest of deployment tools

### PR DESCRIPTION
**Pull request by rmm-fcul**
closes issue #29 

I updated version number to 0.9.1, not sure whether an interface change should do a 0.x+1.y or a 0.x.y+1. So few lines of change ==> I opted for y+1.

### CODE REVIEW

**Comment by dmiklic** [comment]
Why this change? My rationale was that `sim.py` only needs data contained in the `.arena` file. Do you have an use-case where `sim.py` needs some info contained in `.dep` and/or `.nbg`?

According to the [semantic versioning](http://semver.org/) scheme that we are using (or at least attempting to use :) a backwards-incopmatible API change requres a bump in the major version. Althought, our relase being major 0 implies that the API can change, so i guess just a minor version bump (i.e. x+1) should be ok in this case.

**Comment by dmiklic** [comment]
@rmm-fcul as discussed per e-mail, I now understand you rationale and agree that the user should be able to invoke `sim.py` with the `.assisi` file. However, I also see an use case for invoking it with an `.arena` file only (I personally use it that way a lot when testing things :), so I'd like to keep that option.

In short, can you please modify your pull request so that the code checks if it has received an `.arena` or `.assisi` file and does the right thing automatically?

**Comment by rmm-fcul** [comment]
@dmiklic  I've updated the code to branch on the file extension (and tested).

I realised during the coding that it makes the assumption that a .assisi file only refers to a .arena file, and not to a .bees file.  I've never used a .bees file before testing today, and we haven't mentioned these in training.  Accordingly, I vote to include this change as-is, close the issue, and open a separate issue regarding the .bees files if they start to be used. (also to generalise to .fish / .agents etc as needed).

**Comment by rmm-fcul** [comment]
I was thinking about this and re-did the solution to handle .assisi files that define either or both .bees and .arena files. Everything defined will now be spawned, if `sim.py project.assisi` is executed.

**Comment by rmm-fcul** [comment]
@dmiklic any problems with the proposed changes? (either 008ecd6 or failing that, f1db59f)

**Pull request merged**
